[package]
name = "clmul"
version = "0.5.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/apps4uco/clmul"
documentation = "https://docs.rs/clmul"
keywords = ["clmul", "morton", "intrinsic"]
categories=["algorithms","encoding","hardware-support","mathematics","no-std"]
rust-version = "1.70"
description="Carry-less multiply for Rust, internally uses compiler intrinsics, with fallback if the CPU has no clmul instruction"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
morton = "0.3.0"
morton-encoding = "2.0.1"
morton-index = "0.3.0"
zorder = "0.2.2"

[[bench]]
name = "benchmark"
harness = false
